config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "documentary/create"
  get "documentary/index"
  get "documentary/new"
  post "documentaryfilms" => "documentary#create"
  post "documentary" => "documentary#create"

  get "series/index"
  get "series/create"
  get "series/new"
  post "series" => "series#create"

  
  get "movies/index"
  get "movies/create"
  get "movies/new"
  post "movies" => "movies#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentaryfilm.rb
class Documentaryfilm < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/documentary_controller.rb
class DocumentaryController < ApplicationController
  def index
    @documentary_all = Documentaryfilm.all
    end
    
    def new
      @documentary = Documentaryfilm.new
    end
  
      
        def create
          @documentary = Documentaryfilm.new(documental_params)
          if @documentary.save
          redirect_to documentary_index_path
          else
          render :new
          end
        end
      
    
      
      private
       def documental_params
       params.require(:documentaryfilm).permit(:name, :synopsis, :director)
      end
    end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
@movie_all = Movie.all
end

  
    def create
      @movie = Movie.new(movies_params)
      if @movie.save
      redirect_to movies_index_path
      else
      render :new
      end
    end
  

  def new
    @movie = Movie.new
  end

  private
   def movies_params
   params.require(:movie).permit(:name, :synopsis, :director)
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @serie_all = Serie.all
    end
    
      
        def create
          @serie = Serie.new(series_params)
          if @serie.save
          redirect_to series_index_path
          else
          render :new
          end
        end
      
    
      def new
        @serie = Serie.new
      end
    
      private
       def series_params
       params.require(:serie).permit(:name, :synopsis, :director)
      end
    end
    

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_helper.rb
module DocumentaryHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/documentary/create.html.erb
<h1>Documentary#create</h1>
<p>Find me in app/views/documentary/create.html.erb</p>

app/views/documentary/index.html.erb
<h1 class="text-danger-emphasis">Documentary#index</h1>
<p class="text-danger">Listados de Documentales</p>

<% @documentary_all.each do |documental| %>
    <h2><%= documental.name %></h2>
    <p class="text-success"><%= documental.synopsis %></p>
    <p class="text-success"><%= documental.director %></p>
    <% end%>

app/views/documentary/new.html.erb
<h1 class="text-danger">Documentary#new</h1>
<p class="text-danger-emphasis">Ingresar nuevo documental</p>

<%= form_with model: @documentary, method: :post do |form| %>
    <div class="col-4">
        <div class="text-success">
            <%= form.label :title, "Nombre documental" , class: "form-label" %>
                <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="text-success">
            <%= form.label :content, "Sinopsis" , class: "form-label" %>
                <%= form.text_field :synopsis, class: "form-control" %>
        </div>
        <div class="text-success">
            <%= form.label :title, "Nombre director" , class: "form-label" %>
                <%= form.text_field :director, class: "form-control" %>
        </div>
        <div>
            <%= form.submit "Submit" , class: "btn btn-success" %>
        </div>
    </div>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Movies" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
  <div class=container>
  <button> <%= link_to "Listar Peliculas", movies_index_path %> </button>
  <button> <%= link_to "Crear Pelicula", movies_new_path %> </button>
  
  <button> <%= link_to "Listar series", series_index_path %> </button>
  <button> <%= link_to "Crear series", series_new_path %> </button>

  <button> <%= link_to "Listar documentales", documentary_index_path %> </button>
  <button> <%= link_to "Crear documental", documentary_new_path %> </button>

    <%= yield %>
  </div> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/index.html.erb
<h1 class="text-warning">Movies#index</h1>
<p class="text-warning-emphasis">Listado de peliculas</p>

<%  @movie_all.each do |pelicula| %>
    <h2><%= pelicula.name %></h2>
    <p class="text-primary-emphasis"><%= pelicula.synopsis %></p>
    <p class="text-success"><%= pelicula.director %></p>
    <% end%>

app/views/movies/new.html.erb
<h1 class="text-danger">Movies#new</h1>
<p class="text-danger-emphasis">Ingresar Pelicula Nueva</p>

<%= form_with model: @movie, method: :post do |form| %>
    <div class="col-4">
        <div class="text-success">
            <%= form.label :title, "Nombre pelicula" , class: "form-label" %>
                <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="text-success">
            <%= form.label :content, "Sinopsis" , class: "form-label" %>
                <%= form.text_field :synopsis, class: "form-control" %>
        </div>
        <div class="text-success">
            <%= form.label :title, "Nombre director" , class: "form-label" %>
                <%= form.text_field :director, class: "form-control" %>
        </div>
        <div>
            <%= form.submit "Submit" , class: "btn btn-success" %>
        </div>
    </div>
    <% end %>

app/views/series/create.html.erb
<h1>Series#create</h1>
<p>Find me in app/views/series/create.html.erb</p>

app/views/series/index.html.erb
<h1 class="text-primary">Series#index</h1>
<p class="text-primary-emphasis">Listado de series</p>

<% @serie_all.each do |serial| %>
    <h2><%= serial.name %></h2>
    <p class="text-primary-emphasis"><%= serial.synopsis %></p>
    <p class="text-info"><%= serial.director %></p>
    <% end%>

app/views/series/new.html.erb
<h1 class="text-danger">Series#new</h1>
<p class="text-danger-emphasis">Ingresar Serie Nueva</p>

<%= form_with model: @serie, method: :post do |form| %>
    <div class="col-4">
        <div class="text-success">
            <%= form.label :title, "Nombre serie" , class: "form-label" %>
                <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="text-success">
            <%= form.label :content, "Sinopsis" , class: "form-label" %>
                <%= form.text_field :synopsis, class: "form-control" %>
        </div>
        <div class="text-success">
            <%= form.label :title, "Nombre director" , class: "form-label" %>
                <%= form.text_field :director, class: "form-control" %>
        </div>
        <div>
            <%= form.submit "Submit" , class: "btn btn-success" %>
        </div>
    </div>
    <% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>